/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
import java.sql.*;
public class PaymentFrame extends javax.swing.JFrame {
    
    static String Movie; 
    public static double TotAmt;
    
    
    /**
     * Creates new form PaymentFrame
     */
    public PaymentFrame() {
        initComponents();
        lTotalAmount.setText("Total Amount:"+TotAmt);
        setTitle("Payment of Rs."+TotAmt+"  |  Movie: "+Movie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTotalAmount = new javax.swing.JLabel();
        lUpiId = new javax.swing.JLabel();
        lPin = new javax.swing.JLabel();
        tfUpiId = new javax.swing.JTextField();
        pPin = new javax.swing.JPasswordField();
        bPay = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        cbPaymentMode = new javax.swing.JComboBox<>();
        lPaymentMode = new javax.swing.JLabel();
        lMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Payment of Rs.");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lTotalAmount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lTotalAmount.setText("Total Amount:");

        lUpiId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lUpiId.setText("Enter UPI/ Card No.:");

        lPin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPin.setText("Enter PIN:");

        tfUpiId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUpiId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUpiIdActionPerformed(evt);
            }
        });

        pPin.setColumns(6);
        pPin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPinActionPerformed(evt);
            }
        });

        bPay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bPay.setText("Pay");
        bPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPayActionPerformed(evt);
            }
        });

        bCancel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        cbPaymentMode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbPaymentMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BHIM/UPI", "Credit Card", "Net Banking" }));
        cbPaymentMode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPaymentModeItemStateChanged(evt);
            }
        });
        cbPaymentMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaymentModeActionPerformed(evt);
            }
        });

        lPaymentMode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lPaymentMode.setText("Choose Payment Mode:");

        lMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTotalAmount)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bPay)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lUpiId)
                                    .addComponent(lPin)
                                    .addComponent(lPaymentMode))
                                .addGap(82, 82, 82)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPaymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCancel)
                            .addComponent(tfUpiId, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPaymentMode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUpiId)
                    .addComponent(tfUpiId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPin)
                    .addComponent(pPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lMessage)
                .addGap(18, 18, 18)
                .addComponent(lTotalAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPay)
                    .addComponent(bCancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUpiIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUpiIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUpiIdActionPerformed

    private void bPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPayActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/db1";
            Connection con = DriverManager.getConnection(url,"root","");
            Statement s = con.createStatement();
            String userId = tfUpiId.getText();
            String pin = new String(pPin.getPassword());
            String query = "Select password, balance from payment where userid ='"+userId+"'";
            ResultSet rs = s.executeQuery(query);
            String pwd; double bal;
                if(!rs.next()) lMessage.setText("Account Not Found");
                else{
                    pwd = rs.getString(1); bal = rs.getDouble(2);
                    if(!pwd.equals(pin)) lMessage.setText("Incorrect Password");
                    else{
                        if (bal<TotAmt){
                            PaymentBalanceError.caller(TotAmt, bal);
                        }
                        else{
                            String qry = "Update payment set balance = "+(bal-TotAmt)+" where userid = '"+userId+"'";
                            s.executeUpdate(qry);
                            ResultSet rs1 = s.executeQuery(query); rs1.next();
                            
                            TicketConfirmation.caller();
                            dispose();
                        }
                    }
                }
        }
        catch(ClassNotFoundException e){}
        catch(SQLException e){
        System.out.println(e);
        }    
    }//GEN-LAST:event_bPayActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        SeatSelector.f.setVisible(true);
    }//GEN-LAST:event_bCancelActionPerformed

    private void cbPaymentModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaymentModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPaymentModeActionPerformed

    private void pPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPinActionPerformed

    private void cbPaymentModeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPaymentModeItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbPaymentModeItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dispose();
        SeatSelector.f.setVisible(true);
        System.out.println("sadf");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    
    public static void Caller(String movie, double totAmt){
        Movie = movie; TotAmt = totAmt;
        main(new String[1]);
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bPay;
    private javax.swing.JComboBox<String> cbPaymentMode;
    private javax.swing.JLabel lMessage;
    private javax.swing.JLabel lPaymentMode;
    private javax.swing.JLabel lPin;
    private javax.swing.JLabel lTotalAmount;
    private javax.swing.JLabel lUpiId;
    private javax.swing.JPasswordField pPin;
    private javax.swing.JTextField tfUpiId;
    // End of variables declaration//GEN-END:variables
}
