/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */

import java.io.FileOutputStream;
import java.sql.*;
import java.io.*;

public class TicketConfirmation extends javax.swing.JFrame {

    /**
     * Creates new form TicketConfirmation
     */
    
    static String tcMovie, tcSeatString;
    static double totAmt;
    static TicketConfirmation tkt;
    
    
    public static void caller(){
        main(new String[1]);
        tcMovie = SeatSelector.Movie; 
        tcSeatString = SeatSelector.seatString.substring(6, SeatSelector.seatString.length()-7);
        totAmt = PaymentFrame.TotAmt;
    }
    public TicketConfirmation() {
        initComponents();
        lMovie.setText("Movie: "+tcMovie);
        lSeatNumbers.setText("<html> Seat Numbers : "+tcSeatString+"</html>");
        lTotAmt.setText("Total Amount: "+totAmt);
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/db1";
        Connection con = DriverManager.getConnection(url,"root","");
        Statement s = con.createStatement();
        String Query = "insert into tickets values('"+tcMovie+"','"+tcSeatString+"')";
        s.executeUpdate(Query);
        }
        catch(ClassNotFoundException e){
            System.out.println(e);
        }
        catch(SQLException e){System.out.println(e);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lMovie = new javax.swing.JLabel();
        lSeatNumbers = new javax.swing.JLabel();
        bHomePage = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        lMoviePoster = new javax.swing.JLabel();
        lTotAmt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ticket Confirmation");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 157, 0));
        jLabel1.setText("Tickets Booked Successfully");

        lMovie.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lMovie.setText("Movie : ");

        lSeatNumbers.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lSeatNumbers.setText("Seat Numbers : ");

        bHomePage.setText("Home Page");
        bHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHomePageActionPerformed(evt);
            }
        });

        bExit.setText("Exit Application");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        lMoviePoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+tcMovie+".png")));

        lTotAmt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lTotAmt.setText("Total Amount: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(bExit))
                            .addComponent(lSeatNumbers)
                            .addComponent(lMovie)
                            .addComponent(jLabel1)
                            .addComponent(lTotAmt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lMoviePoster)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(lMovie)
                .addGap(18, 18, 18)
                .addComponent(lMoviePoster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(lSeatNumbers)
                .addGap(34, 34, 34)
                .addComponent(lTotAmt)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHomePage)
                    .addComponent(bExit))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHomePageActionPerformed
        // TODO add your handling code here:
        dispose();
        HomePageFrame.main(new String[1]);
    }//GEN-LAST:event_bHomePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tkt = new TicketConfirmation();
                tkt.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bHomePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lMovie;
    private javax.swing.JLabel lMoviePoster;
    private javax.swing.JLabel lSeatNumbers;
    private javax.swing.JLabel lTotAmt;
    // End of variables declaration//GEN-END:variables
}


class tkt implements Serializable{
               String movie, seats;
               double tAmt;
               tkt(String tcMovie, String tcSeatString, double totAmt){
                   movie = tcMovie;
                   seats = tcSeatString;
                   tAmt = totAmt;
               }
           }